api = "0.6"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/node-run-script"
  id = "paketo-buildpacks/node-run-script"
  name = "Paketo Node Run Script Buildpack"

[metadata]
  include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
